//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.27 at 11:10:43 AM IST 
//


package com.samsung.trailer.xsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="select" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fields" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="sort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="skip" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="update" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="update-field" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="multi-update" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="delete" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="aggregate" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pipline-sql" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "select",
    "update",
    "delete",
    "aggregate"
})
@XmlRootElement(name = "mongo-sql")
public class MongoSql {

    protected List<MongoSql.Select> select;
    protected List<MongoSql.Update> update;
    protected List<MongoSql.Delete> delete;
    protected List<MongoSql.Aggregate> aggregate;

    /**
     * Gets the value of the select property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the select property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MongoSql.Select }
     * 
     * 
     */
    public List<MongoSql.Select> getSelect() {
        if (select == null) {
            select = new ArrayList<MongoSql.Select>();
        }
        return this.select;
    }

    /**
     * Gets the value of the update property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the update property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpdate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MongoSql.Update }
     * 
     * 
     */
    public List<MongoSql.Update> getUpdate() {
        if (update == null) {
            update = new ArrayList<MongoSql.Update>();
        }
        return this.update;
    }

    /**
     * Gets the value of the delete property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delete property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelete().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MongoSql.Delete }
     * 
     * 
     */
    public List<MongoSql.Delete> getDelete() {
        if (delete == null) {
            delete = new ArrayList<MongoSql.Delete>();
        }
        return this.delete;
    }

    /**
     * Gets the value of the aggregate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MongoSql.Aggregate }
     * 
     * 
     */
    public List<MongoSql.Aggregate> getAggregate() {
        if (aggregate == null) {
            aggregate = new ArrayList<MongoSql.Aggregate>();
        }
        return this.aggregate;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pipline-sql" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "piplineSql"
    })
    public static class Aggregate {

        @XmlElement(name = "pipline-sql")
        protected List<String> piplineSql;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the piplineSql property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the piplineSql property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPiplineSql().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPiplineSql() {
            if (piplineSql == null) {
                piplineSql = new ArrayList<String>();
            }
            return this.piplineSql;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "findSql"
    })
    public static class Delete {

        @XmlElement(name = "find-sql", required = true)
        protected String findSql;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the findSql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFindSql() {
            return findSql;
        }

        /**
         * Sets the value of the findSql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFindSql(String value) {
            this.findSql = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fields" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="sort" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="limit" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="skip" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "findSql",
        "fields",
        "sort",
        "limit",
        "skip"
    })
    public static class Select {

        @XmlElement(name = "find-sql", required = true)
        protected String findSql;
        protected String fields;
        @XmlElement(required = true)
        protected String sort;
        protected byte limit;
        protected byte skip;
        @XmlAttribute(name = "id")
        protected String id;

        /**
         * Gets the value of the findSql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFindSql() {
            return findSql;
        }

        /**
         * Sets the value of the findSql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFindSql(String value) {
            this.findSql = value;
        }

        /**
         * Gets the value of the fields property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFields() {
            return fields;
        }

        /**
         * Sets the value of the fields property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFields(String value) {
            this.fields = value;
        }

        /**
         * Gets the value of the sort property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSort() {
            return sort;
        }

        /**
         * Sets the value of the sort property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSort(String value) {
            this.sort = value;
        }

        /**
         * Gets the value of the limit property.
         * 
         */
        public byte getLimit() {
            return limit;
        }

        /**
         * Sets the value of the limit property.
         * 
         */
        public void setLimit(byte value) {
            this.limit = value;
        }

        /**
         * Gets the value of the skip property.
         * 
         */
        public byte getSkip() {
            return skip;
        }

        /**
         * Sets the value of the skip property.
         * 
         */
        public void setSkip(byte value) {
            this.skip = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="find-sql" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="update-field" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="multi-update" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "findSql",
        "updateField"
    })
    public static class Update {

        @XmlElement(name = "find-sql", required = true)
        protected String findSql;
        @XmlElement(name = "update-field", required = true)
        protected String updateField;
        @XmlAttribute(name = "id")
        protected String id;
        @XmlAttribute(name = "multi-update")
        protected String multiUpdate;

        /**
         * Gets the value of the findSql property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFindSql() {
            return findSql;
        }

        /**
         * Sets the value of the findSql property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFindSql(String value) {
            this.findSql = value;
        }

        /**
         * Gets the value of the updateField property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpdateField() {
            return updateField;
        }

        /**
         * Sets the value of the updateField property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpdateField(String value) {
            this.updateField = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the multiUpdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMultiUpdate() {
            return multiUpdate;
        }

        /**
         * Sets the value of the multiUpdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMultiUpdate(String value) {
            this.multiUpdate = value;
        }

    }

}
